[package]
name = "gbridge-bridge"
version = "0.4.0"
authors = ["Pascal Hartig <phartig@rdrei.net>"]
edition = "2018"

[dependencies]
rumqtt = "0.30.1"
failure = "0.1.5"
phf = "0.7.24"
phf_macros = "0.7.24"
toml = "0.5.0"
serde = { version = "1.0.91", features = ["derive"] }
