[package]
name = "gbridge-bridge"
version = "0.5.2"
authors = ["Pascal Hartig <phartig@rdrei.net>"]
edition = "2018"

[dependencies]
rumqtt = "0.31.0"
failure = "0.1.6"
phf = "0.8.0"
phf_macros = "0.8.0"
toml = "0.5.5"
serde = { version = "1.0.102", features = ["derive"] }
log = "0.4.8"
pretty_env_logger = "0.3.1"
